version: '3.8'

services:
  # Development Frontend
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
      - API_BASE_URL=http://localhost:8000
      - NEXT_PUBLIC_ENVIRONMENT=development
      - NEXT_PUBLIC_DEBUG_MODE=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - cuentas-claras-dev
    restart: unless-stopped

  # Development Database
  db-dev:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=cuentas_claras_dev
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
    ports:
      - '5433:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - cuentas-claras-dev
    restart: unless-stopped

  # Development Redis
  redis-dev:
    image: redis:7-alpine
    ports:
      - '6380:6379'
    volumes:
      - redis_dev_data:/data
    networks:
      - cuentas-claras-dev
    restart: unless-stopped

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  cuentas-claras-dev:
    driver: bridge
